// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nknxthtxlzwvmmvxaqry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbnh0aHR4bHp3dm1tdnhhcXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTU4NjcsImV4cCI6MjA2NjMzMTg2N30.KZLI4HKpgxBKhJSyJ_kA3XxLX2Mwq0dnSaFipkdZvrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);